# Generated by Django 5.1.3 on 2025-01-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locker_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Beer', 'Beer'), ('Wine', 'Wine'), ('Spirits', 'Spirits'), ('Cocktails', 'Cocktails'), ('Mixers', 'Mixers')], max_length=50, null=True),
        ),
    ]
