# Generated by Django 5.1.3 on 2025-01-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locker_Api', '0003_product_description_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Enter product SKU number', max_length=50, null=True),
        ),
    ]
